### ISSUE TITLE
Blank PDF pages

### ISSUE THREAD

**Issue by jmester13** [kogmbh/ViewerJS#88] opened 2014-09-05 17:01 UTC
Hello All, 

First off thank you for this tool, it is awesome and I've enjoyed learning about it! I've hit a bit of a issue I'm hoping someone might be able to help me with. I am embedding PDF documents which have been created via Adobe LiveCycle and have run into an issue where the documents pages are loaded but appear blank. If I click on the download button the document loads up without issue and I can scroll without issue. Does anyone have a thought on why I am not able to see document text within the iframe? 

All other PDF's seem to work fine, its just Adobe LiveCycle ones that seem to be causing an issue. 

Any help you can offer would be great.

**Comment by forloops** [comment] 2015-02-09 14:18
@akszydelko - your fix works. Thank you for sharing

**Comment by kossebau** [comment] 2015-02-12 22:20
While I could not reproduce the problem even with the provided PDF the problem @akszydelko found and has described I also see in theory.
ViewerJS 0.5.5 has been released today, and it comes with https://github.com/kogmbh/ViewerJS/commit/7e9ad23f0ead4ef608e08c9352f8bd1d129d065b which should ensure the proper order while still making use of the async calls to speedup the loading.
Please try if this new version also works for you and the PDFs you experience problems. (The version of pdf.js was also updated to the latest official release, BTW).
Closing this issue for now, please reopen if there are still problems also with pure 0.5.5.

**Closed by kossebau** 2015-02-12 22:20 UTC
Labels: bug, PDF.js

**Comment by simonhayes81** [comment] 2015-02-13 09:13
I’m still having problems. It seems to work fine in Google Chrome, but in Internet Explorer the PDF takes ages to load and when it does the text is all garbled.

**Comment by kossebau** [comment] 2015-02-13 12:16
@simonhayes81 Which version is your Internet Explorer? For what I tested with latest IE10 it seems fine.
Is the PDF you are trying public, so I could test with it as well?

**Comment by simonhayes81** [comment] 2015-02-13 12:18
IE11

I've put it up here: http://www.brookvalehighschool.co.uk/pages/home/prospectus.html

**Comment by kossebau** [comment] 2015-02-13 12:29
Ah, that pdf, even part of my testing set :) Hm, that page works fine in IE10 for me (besides taking some time without any feedback/loading screen, but that is a different issue, tracked in #96).

No IE11 available right now, anyone else could confirm? So far hoping it is a caching issue perhaps? :)

**Comment by simonhayes81** [comment] 2015-02-13 12:30
On further examination, it seems to work fine on Windows 10 in IE 11, but not in Windows 7.

**Comment by kossebau** [comment] 2015-02-13 12:33
Could you post a screenshot to get a better idea what "text is all garbled." means?
What I see is that the invisible text layer for selection seems not properly calculated, so it is off for most of the text. That would be an issue in pdf.js, nothing ViewerJS can do about.

**Comment by simonhayes81** [comment] 2015-02-13 12:49
Just done some more testing, and in actual fact it does load properly on Windows 7 with IE11, but takes a very very long time to load (around 2 minutes), an unacceptable amount of time in fact because almost everyone would have given up by then.

Windows 8 IE11 takes too long to load and also has the garbled text problem which I will post in a minute.

Windows 10 IE11 which I'm running on Hyper-V works fine, loads pretty much instantly and the text is as it should be.

**Comment by simonhayes81** [comment] 2015-02-13 12:57
http://www.brookvalehighschool.co.uk/pages/home/garbled.png

That's the shot where the text is garbled.

I suppose you could argue that people shouldn't be using IE and definitely shouldn't be using Windows 8, but would rather find a solution!

**Comment by kossebau** [comment] 2015-02-13 13:09
Thanks, I see. Not using IE would indeed be a solution :) but right, reality is what we are here for.

Very possibly some issue in pdf.js then. Nothing I can help with just a few finger snips.

No (free) time to look deeper into that myself, sorry. So it's either hoping someone else has energy and resources to dive into that and see what needs fixing and then fix it. Or you investing into someone doing that (where I of course recommend contacting viewerjs-support@kogmbh.com but then working patches will be accepted for ViewerJS/pdf.js independent of who created them :) ).

**Comment by simonhayes81** [comment] 2015-02-13 13:11
Any ideas why it would do this on Windows 8, but not Windows 7 or Windows 10?

**Comment by Tambe257** [comment] 2015-11-19 20:54
I also have a large pdf the loads super slowly and ends up with blank pages. I don't see a file called PDFViewerPlugin.js when I download the zip file from viewerjs.org. Should I be downloading it directly from Github?

**Comment by fmp777** [comment] 2016-04-26 15:49
Getting complaints from IE 11 users myself, had a staff member test and they can reproduce. Edge works fine.  Any motion on this?
