### ISSUE TITLE
Viewer only loaded two first pages

### ISSUE THREAD

**Issue by fellipefingoli** [kogmbh/ViewerJS#125] opened 2015-03-04 18:34 UTC
I've a probleme while using Viewer JS. My PDF file only load the first two pages, the others simply doesn't show. The page numbers are correct but the scroll bar and the page changes buttons only show two pages. Sometimes the viewer is stuck on a random page.
I get this error on console : Uncaught TypeError: Cannot read property 'resolve' of null in line 25 in line 2531.

**Comment by kossebau** [comment] 2015-03-04 18:37
Hi. Which version of the PDF plugin are you using? See the about dialog when clicking on the "ViewerJS" button. And is your PDF somehow accessible, so we could check ourselves? Or could you send it to friedrich@kogmbh.com at least?

**Comment by fellipefingoli** [comment] 2015-03-04 19:10
Hi. Thank you for response. The version is: 
     Using the PDF.js (v1.0.907) plugin to show you this document.
I already update the PDF.js plugin to the last stable version and I got the same error. 
Unfortunately the pdf is private but I will see what I can do about send you a PDF with this error.

**Comment by fellipefingoli** [comment] 2015-03-04 19:23
Ok, I've an authorization for share the file with you. Just to ilustrate better, when I used the vanilla viewer like this http://mozilla.github.io/pdf.js/examples/learning/prevnext.html, I got no error.

**Comment by kossebau** [comment] 2015-03-04 19:44
Thanks, received. Will investigate tomorrow morning. If it works in the vanilla viewer, that indeed seems like that is something that can be fixed in ViewerJS.

**Comment by kossebau** [comment] 2015-03-13 12:23
(Pardon, only found time to look into the issue today)
Seems the problem is that some code parts of ViewerJS assume constant page sizes, which your PDF does not have. :no_good: 
Currently seeing if that assumptions can be removed without cutting too many strings, not sure yet.

**Comment by kossebau** [comment] 2015-03-16 13:57
Should be fixed with latest ViewerJS 0.5.6 of today, so closing this issue now.
Please get the latest version from viewerjs.org, and reopen if there still is a problem.

**Closed by kossebau** 2015-03-16 13:57 UTC
